# This is a config for E2B sandbox template.
# You can use template ID (wgsqypze7abzcfj30kue) or template name (vibe-nextjs-kaif-123-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-kaif-123-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-kaif-123-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-kaif-123-2')

team_id = "7c60e176-c109-41b0-ab8b-1ef75e9aa767"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-kaif-123-2"
template_id = "wgsqypze7abzcfj30kue"
